// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.2
// - protoc             v3.21.3
// source: SsoDubboProvider.proto

package dubbo_api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// SsoDubboProviderClient is the client API for SsoDubboProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SsoDubboProviderClient interface {
	PasswordLogin(ctx context.Context, in *PasswordLoginReq, opts ...grpc_go.CallOption) (*LoginRsp, common.ErrorWithAttachment)
}

type ssoDubboProviderClient struct {
	cc *triple.TripleConn
}

type SsoDubboProviderClientImpl struct {
	PasswordLogin func(ctx context.Context, in *PasswordLoginReq) (*LoginRsp, error)
}

func (c *SsoDubboProviderClientImpl) GetDubboStub(cc *triple.TripleConn) SsoDubboProviderClient {
	return NewSsoDubboProviderClient(cc)
}

func NewSsoDubboProviderClient(cc *triple.TripleConn) SsoDubboProviderClient {
	return &ssoDubboProviderClient{cc}
}

func (c *ssoDubboProviderClient) PasswordLogin(ctx context.Context, in *PasswordLoginReq, opts ...grpc_go.CallOption) (*LoginRsp, common.ErrorWithAttachment) {
	out := new(LoginRsp)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/PasswordLogin", in, out)
}

// SsoDubboProviderServer is the server API for SsoDubboProvider service.
// All implementations must embed UnimplementedSsoDubboProviderServer
// for forward compatibility
type SsoDubboProviderServer interface {
	PasswordLogin(context.Context, *PasswordLoginReq) (*LoginRsp, error)
	mustEmbedUnimplementedSsoDubboProviderServer()
}

// UnimplementedSsoDubboProviderServer must be embedded to have forward compatible implementations.
type UnimplementedSsoDubboProviderServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedSsoDubboProviderServer) PasswordLogin(context.Context, *PasswordLoginReq) (*LoginRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PasswordLogin not implemented")
}
func (s *UnimplementedSsoDubboProviderServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedSsoDubboProviderServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedSsoDubboProviderServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &SsoDubboProvider_ServiceDesc
}
func (UnimplementedSsoDubboProviderServer) mustEmbedUnimplementedSsoDubboProviderServer() {}

// UnsafeSsoDubboProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SsoDubboProviderServer will
// result in compilation errors.
type UnsafeSsoDubboProviderServer interface {
	mustEmbedUnimplementedSsoDubboProviderServer()
}

func RegisterSsoDubboProviderServer(s grpc_go.ServiceRegistrar, srv SsoDubboProviderServer) {
	s.RegisterService(&SsoDubboProvider_ServiceDesc, srv)
}

func _SsoDubboProvider_PasswordLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("PasswordLogin", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SsoDubboProvider/PasswordLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsoDubboProviderServer).PasswordLogin(ctx, req.(*PasswordLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SsoDubboProvider_ServiceDesc is the grpc_go.ServiceDesc for SsoDubboProvider service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var SsoDubboProvider_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "SsoDubboProvider",
	HandlerType: (*SsoDubboProviderServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "PasswordLogin",
			Handler:    _SsoDubboProvider_PasswordLogin_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "SsoDubboProvider.proto",
}
